name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc, aarch64-pc-windows-msvc, i686-pc-windows-msvc

    - name: Build x64
      run: cargo build --release --verbose --target=x86_64-pc-windows-msvc
    - name: Upload x64
      uses: actions/upload-artifact@v4
      with:
        name: gc-x_x64
        path: target/x86_64-pc-windows-msvc/release/gc-x.exe

    - name: Build arm64
      run: cargo build --release --verbose --target=aarch64-pc-windows-msvc
    - name: Upload arm64
      uses: actions/upload-artifact@v4
      with:
        name: gc-x_arm64
        path: target/aarch64-pc-windows-msvc/release/gc-x.exe

    - name: Build x86
      run: cargo build --release --verbose --target=i686-pc-windows-msvc
    - name: Upload x86
      uses: actions/upload-artifact@v4
      with:
        name: gc-x_x86
        path: target/i686-pc-windows-msvc/release/gc-x.exe

    - name: Set up bundle
      run: |
        copy target/x86_64-pc-windows-msvc/release/gc-x.exe gc-x_x64.exe
        copy target/aarch64-pc-windows-msvc/release/gc-x.exe gc-x_arm64.exe
        copy target/i686-pc-windows-msvc/release/gc-x.exe gc-x_x86.exe
    - name: Upload bundle
      uses: actions/upload-artifact@v4
      with:
        name: bundle
        path: gc-x_*.exe
